name: Build Drop CTRL OpenRGB

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:3.11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Allow git in container
        run: |
          git config --global --add safe.directory '*'

      - name: Install Python dependencies
        run: |
          /opt/uv/tools/qmk/bin/python3 -m pip install -r requirements.txt

      - name: Build firmware
        run: |
          qmk compile -kb massdrop/ctrl -km openrgb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Drop-CTRL-OpenRGB
          path: .build/
