name: Build Drop CTRL Firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: 0.26.11
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi python3-pip
          python3 -m pip install qmk

      - name: QMK Compile
        run: |
          # The standard way to initialize and build
          python3 -m qmk.cli setup -y
          python3 -m qmk.cli compile -kb massdrop/ctrl -km openrgb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Drop-CTRL-OpenRGB
          path: .build/*.bin
